config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get  "/help"     => "static_pages#help"
  get  "/about"    => "static_pages#about"
  get  "/signup"   => "users#new"
  resources :users
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :words
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :results
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :user
  belongs_to :lesson
  belongs_to :word
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}

  has_many :activities
  has_many :lessons
  has_many :results
  has_many :active_relationships, class_name: "Relationship",
    foreign_key: "follower_id", dependent: :destroy

  validates :name, presence: true, length: {maximum: Settings.user_name_max}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.user_email_max},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: Settings.user_password_min}, allow_nil: true

  has_secure_password
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = t("flash-signup-success")
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
      :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = t("title")
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      <%= t("logo") %>
    </small>
    <nav>
      <ul>
        <li><%= link_to t("about"), about_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("logo"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("home"), root_path %></li>
        <li><%= link_to t("help"), help_path %></li>
        <li><%= link_to t("about"), about_path %></li>
        <li class="signup-menu"><%= link_to t("signup"), signup_path %></li>
        <li class="signup-menu"><%= link_to t("login"), "#" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track"=> true %>
    <%= javascript_include_tag "application", "data-turbolinks-track"=> true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "shared/alert_flash" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_alert_flash.html.erb
<% if flash.any? %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t("contain-error") %> <%= pluralize(object.errors.count, t("error")) %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, t("about")) %>
<h1><%= t("about_title") %></h1>
<div class="about">
  <%= image_tag("image_about1.jpg", alt: "img1") %>
  <p><%= t("about_para1") %></p>
  <p><%= t("about_para2") %></p>
  <p><%= t("about_para3") %></p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, t("help")) %>
<%= image_tag("support.jpeg", class: "help_photo") %>
<h3><%= t("help_title") %></h3>

app/views/static_pages/home.html.erb
<% provide(:title, t("home")) %>
<%= image_tag("banner.jpg", alt: "e-learning", class: "home_photo") %>
<div class="center jumbotron">
  <h1><%= t("welcome") %></h1>
  <h2><%= t("slogan") %></h2>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: @user %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation, t("password-confirm") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.submit t("account-create"), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, t("signup")) %>
<h1><%= t("signup") %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<%= image_tag("profilelogo.png", class: "profile_logo") %>
<h1 class="show_title"><%= @user.name %><%= t("profile") %></h1>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h4> <%= t("username") %>: <%= @user.name %> </h4>
      <h4> <%= t("username") %>: <%= @user.email %></h4>
      <h4> <%= t("registation-time") %>: <%= @user.created_at %>
      <h4> <%= t("follower") %>: </h4>
      <h4> <%= t("follow") %>: </h4>
      <h4> <%= t("complete-lesson") %>: </h4>
      <h4> <%= t("point") %>: </h4>
    </section>
  </aside>
</div>